# /// script
# requires-python = ">=3.11"
# dependencies = [
#   "PyJWT>=2.8",
# ]
# ///

"""
Generate short-lived HS256 JWTs for the webtrigger integration test suite.

Reads secrets from integration/webtrigger/.env.hurl and writes two JWTs to
integration/webtrigger/.jwt.hurl so that Hurl can use them as Bearer tokens.

Usage:
    npm run test:api:webtrigger:bootstrap
    # or directly:
    uv run integration/webtrigger/generate-jwt.py

Environment variable overrides:
    ENV_FILE         Path to the .env.hurl file (default: integration/webtrigger/.env.hurl)
    JWT_HURL_FILE    Path to write .jwt.hurl    (default: integration/webtrigger/.jwt.hurl)
    JWT_ISSUER       iss claim value            (default: integration-test)
    JWT_EXPIRY_SECS  Token lifetime in seconds  (default: 900 = 15 min)
"""

import datetime
import os
import sys
from pathlib import Path

import jwt  # PyJWT


ENV_FILE_DEFAULT = "integration/webtrigger/.env.hurl"
JWT_HURL_FILE_DEFAULT = "integration/webtrigger/.jwt.hurl"
JWT_ISSUER_DEFAULT = "integration-test"
JWT_EXPIRY_SECS_DEFAULT = 900  # 15 minutes


def read_hurl_env(path: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        values[key.strip()] = value.strip()
    return values


def mint_jwt(secret: str, audience: str, issuer: str, expiry_secs: int) -> str:
    now = datetime.datetime.now(tz=datetime.timezone.utc)
    payload = {
        "iss": issuer,
        "aud": audience,
        "iat": now,
        "exp": now + datetime.timedelta(seconds=expiry_secs),
    }
    return jwt.encode(payload, secret, algorithm="HS256")


def write_jwt_hurl(path: Path, plain_jwt: str, as_user_jwt: str) -> None:
    lines = [
        "# Generated by npm run test:api:webtrigger:bootstrap. Do not commit.",
        f"webtrigger_jwt={plain_jwt}",
        f"webtrigger_as_user_jwt={as_user_jwt}",
    ]
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    env_file = Path(os.environ.get("ENV_FILE", ENV_FILE_DEFAULT))
    jwt_hurl_file = Path(os.environ.get("JWT_HURL_FILE", JWT_HURL_FILE_DEFAULT))
    issuer = os.environ.get("JWT_ISSUER", JWT_ISSUER_DEFAULT)
    expiry_secs = int(os.environ.get("JWT_EXPIRY_SECS", JWT_EXPIRY_SECS_DEFAULT))

    if not env_file.exists():
        raise RuntimeError(
            f"{env_file} does not exist. "
            f"Copy integration/webtrigger/.env.hurl.example to {env_file} first."
        )

    env = read_hurl_env(env_file)

    plain_secret = os.environ.get("WEBTRIGGER_TOKEN") or env.get("webtrigger_token", "")
    as_user_secret = os.environ.get("WEBTRIGGER_AS_USER_TOKEN") or env.get(
        "webtrigger_as_user_token", ""
    )

    if not plain_secret or plain_secret.startswith("<"):
        raise RuntimeError(
            f"Missing or placeholder webtrigger_token in {env_file}. "
            "Set it to the value from: forge variables set WEBTRIGGER_TOKEN"
        )
    if not as_user_secret or as_user_secret.startswith("<"):
        raise RuntimeError(
            f"Missing or placeholder webtrigger_as_user_token in {env_file}. "
            "Set it to the value from: forge variables set WEBTRIGGER_AS_USER_TOKEN"
        )

    print(f"Minting JWTs (iss={issuer!r}, expiry={expiry_secs}s)")

    plain_jwt = mint_jwt(
        secret=plain_secret,
        audience="write:workitem:custom",
        issuer=issuer,
        expiry_secs=expiry_secs,
    )
    as_user_jwt = mint_jwt(
        secret=as_user_secret,
        audience="write:workitem-as-user:custom",
        issuer=issuer,
        expiry_secs=expiry_secs,
    )

    jwt_hurl_file.parent.mkdir(parents=True, exist_ok=True)
    write_jwt_hurl(jwt_hurl_file, plain_jwt, as_user_jwt)

    print(f"Written {jwt_hurl_file} with fresh JWTs")
    print("Bootstrap complete. You can now run: npm run test:api:webtrigger")


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("Interrupted", file=sys.stderr)
        raise SystemExit(130)
    except Exception as error:
        print(f"Error: {error}", file=sys.stderr)
        raise SystemExit(1)
