# /// script
# requires-python = ">=3.14"
# dependencies = []
# ///

import json
import os
import secrets
import sys
import threading
import webbrowser
from http.server import BaseHTTPRequestHandler, HTTPServer
from pathlib import Path
from typing import Any
from urllib.error import HTTPError, URLError
from urllib.parse import parse_qs, quote, urlencode, urlparse
from urllib.request import Request, urlopen

AUTH_BASE_URL = "https://auth.atlassian.com"
REDIRECT_URI_DEFAULT = "http://localhost:9876/callback"
SCOPES_DEFAULT = "write:workitem:custom write:workitem-as-user:custom"


def read_hurl_env(path: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        values[key.strip()] = value.strip()
    return values


def derive_sns(base_url: str) -> str:
    marker = "/apps/"
    if marker not in base_url:
        return ""
    app_env_id = base_url.rsplit(marker, 1)[1].split("/", 1)[0]
    if "_" not in app_env_id:
        return ""
    return app_env_id.replace("_", ".", 1)


def post_form(url: str, form: dict[str, str]) -> dict[str, Any]:
    body = urlencode(form).encode("utf-8")
    request = Request(
        url,
        data=body,
        headers={"Content-Type": "application/x-www-form-urlencoded"},
        method="POST",
    )
    try:
        with urlopen(request, timeout=60) as response:
            return json.loads(response.read().decode("utf-8"))
    except HTTPError as error:
        details = error.read().decode("utf-8", errors="replace")
        raise RuntimeError(f"POST {url} failed with HTTP {error.code}: {details}") from error
    except URLError as error:
        raise RuntimeError(f"POST {url} failed: {error}") from error


class OAuthCallbackHandler(BaseHTTPRequestHandler):
    server: "OAuthCallbackServer"

    def do_GET(self) -> None:  # noqa: N802 - stdlib callback name
        parsed = urlparse(self.path)
        params = parse_qs(parsed.query)
        self.server.query_params = {key: values[0] for key, values in params.items() if values}
        self.send_response(200)
        self.send_header("Content-Type", "text/plain; charset=utf-8")
        self.end_headers()
        self.wfile.write(b"OAuth callback received. You can return to the terminal.\n")
        threading.Thread(target=self.server.shutdown, daemon=True).start()

    def log_message(self, format: str, *args: object) -> None:
        return


class OAuthCallbackServer(HTTPServer):
    query_params: dict[str, str]


def wait_for_authorization_code(auth_url: str, redirect_uri: str, state: str) -> str:
    parsed_redirect = urlparse(redirect_uri)
    if parsed_redirect.hostname not in {"localhost", "127.0.0.1"}:
        raise RuntimeError(f"Only localhost redirect URIs are supported: {redirect_uri}")
    if not parsed_redirect.port:
        raise RuntimeError(f"Redirect URI must include a port: {redirect_uri}")

    server = OAuthCallbackServer(("localhost", parsed_redirect.port), OAuthCallbackHandler)
    server.query_params = {}

    print("Opening OAuth authorization URL in your browser")
    if not webbrowser.open(auth_url):
        print("Open this URL in your browser:")
        print(auth_url)

    print(f"Waiting for OAuth callback on localhost:{parsed_redirect.port}")
    server.serve_forever()
    server.server_close()

    params = server.query_params
    if "error" in params:
        description = params.get("error_description", "")
        raise RuntimeError(f"OAuth authorization failed: {params['error']} {description}".strip())
    if params.get("state") != state:
        raise RuntimeError("OAuth callback state did not match.")
    code = params.get("code")
    if not code:
        raise RuntimeError("OAuth callback did not include a code.")
    return code


def write_oauth_hurl(path: Path, access_token: str, refresh_token: str) -> None:
    lines = [
        "# Generated by npm run test:api:bootstrap. Do not commit.",
        f"oauth_access_token={access_token}",
    ]
    if refresh_token:
        lines.append(f"oauth_refresh_token={refresh_token}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    token_file = Path(os.environ.get("TOKEN_FILE", "integration/access_token_response.json"))
    env_file = Path(os.environ.get("ENV_FILE", "integration/.env.hurl"))
    oauth_hurl_file = Path(os.environ.get("OAUTH_HURL_FILE", "integration/.oauth.hurl"))
    if not env_file.exists():
        raise RuntimeError(
            f"{env_file} does not exist. Copy integration/.env.hurl.example to {env_file} first."
        )

    env = read_hurl_env(env_file)
    client_id = os.environ.get("ATLASSIAN_APP_3LO_CLIENT_ID") or env.get("oauth_client_id", "")
    client_secret = os.environ.get("ATLASSIAN_APP_3LO_CLIENT_SECRET") or env.get(
        "oauth_client_secret", ""
    )
    redirect_uri = os.environ.get("OAUTH_REDIRECT_URI") or env.get(
        "oauth_redirect_uri", REDIRECT_URI_DEFAULT
    )
    scopes = os.environ.get("SCOPES") or env.get("oauth_scopes", SCOPES_DEFAULT)
    sns = os.environ.get("OAUTH_SNS") or env.get("oauth_sns", "") or derive_sns(
        env.get("base_url", "")
    )

    if not client_id:
        raise RuntimeError(f"Missing oauth_client_id in {env_file} or ATLASSIAN_APP_3LO_CLIENT_ID")
    if not client_secret:
        raise RuntimeError(
            f"Missing oauth_client_secret in {env_file} or ATLASSIAN_APP_3LO_CLIENT_SECRET"
        )
    if not sns:
        raise RuntimeError(
            f"Missing oauth_sns in {env_file} or OAUTH_SNS, and could not derive it from base_url"
        )

    token_file.parent.mkdir(parents=True, exist_ok=True)
    oauth_hurl_file.parent.mkdir(parents=True, exist_ok=True)
    refresh_token = ""
    if token_file.exists():
        try:
            token_response = json.loads(token_file.read_text(encoding="utf-8"))
        except json.JSONDecodeError as error:
            raise RuntimeError(
                f"Could not parse {token_file}. Delete it to start a fresh code flow."
            ) from error
        refresh_token = token_response.get("refresh_token", "")

    if refresh_token:
        print("Performing refresh token flow to obtain a fresh access token response")
        print(f"If this step fails, delete '{token_file}' to start with a fresh code flow")
        token_response = post_form(
            f"{AUTH_BASE_URL}/oauth/token",
            {
                "grant_type": "refresh_token",
                "client_id": client_id,
                "client_secret": client_secret,
                "refresh_token": refresh_token,
            },
        )
    else:
        print("Performing authorization code flow to obtain initial access token response")
        print(f"Requesting OAuth scopes: {scopes}")
        print(f"Using OAuth SNS: {sns}")
        state = secrets.token_urlsafe(24)
        auth_url = f"{AUTH_BASE_URL}/authorize?{urlencode({
            'audience': 'api.atlassian.com',
            'client_id': client_id,
            'scope': scopes,
            'redirect_uri': redirect_uri,
            'state': state,
            'response_type': 'code',
            'prompt': 'consent',
            'sns': sns,
        }, quote_via=quote)}"
        code = wait_for_authorization_code(auth_url, redirect_uri, state)
        token_response = post_form(
            f"{AUTH_BASE_URL}/oauth/token",
            {
                "grant_type": "authorization_code",
                "client_id": client_id,
                "client_secret": client_secret,
                "code": code,
                "redirect_uri": redirect_uri,
            },
        )

    access_token = token_response.get("access_token", "")
    new_refresh_token = token_response.get("refresh_token", "")
    if not access_token:
        raise RuntimeError("Missing access token from OAuth response")

    token_file.write_text(json.dumps(token_response, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    write_oauth_hurl(oauth_hurl_file, access_token, new_refresh_token)
    print(f"Updated {oauth_hurl_file} with latest access token")
    print("OAuth bootstrap complete. You can now run: npm run test:api")


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("Interrupted", file=sys.stderr)
        raise SystemExit(130)
    except Exception as error:
        print(f"Error: {error}", file=sys.stderr)
        raise SystemExit(1)
